POST http://localhost:8000/tickers
Content-Type: application/json

{
    "name": "IEF",
    "country": "USA"
}

###
GET http://localhost:8000/tickers

###
POST http://localhost:8000/tickers
Content-Type: application/json

{
    "name": "IEF",
    "country": "usa"
}