services: 
  web:
    env_file:
      - /env/.env.web.dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn api_server.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    env_file:
      - /env/.env.postgres.dev
    image: postgres:17          
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: